// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYkHnSFCc7z-86PCGk6vRsjIBgViBUYjg',
    appId: '1:955735179343:web:5df91d709aaac533a36a3a',
    messagingSenderId: '955735179343',
    projectId: 'instructor-1d9b7',
    authDomain: 'instructor-1d9b7.firebaseapp.com',
    storageBucket: 'instructor-1d9b7.firebasestorage.app',
    measurementId: 'G-0LRWDQT2Z0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBQdXsxmoAeqiPPcD1DsjSy3M1q3su-Vg',
    appId: '1:955735179343:android:ac22abb7efdbb933a36a3a',
    messagingSenderId: '955735179343',
    projectId: 'instructor-1d9b7',
    storageBucket: 'instructor-1d9b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUIclt0uyJN1XFsHZC09dkSrdt9HKMNpA',
    appId: '1:955735179343:ios:5c568cd87a587690a36a3a',
    messagingSenderId: '955735179343',
    projectId: 'instructor-1d9b7',
    storageBucket: 'instructor-1d9b7.firebasestorage.app',
    iosBundleId: 'com.example.instructor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUIclt0uyJN1XFsHZC09dkSrdt9HKMNpA',
    appId: '1:955735179343:ios:5c568cd87a587690a36a3a',
    messagingSenderId: '955735179343',
    projectId: 'instructor-1d9b7',
    storageBucket: 'instructor-1d9b7.firebasestorage.app',
    iosBundleId: 'com.example.instructor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYkHnSFCc7z-86PCGk6vRsjIBgViBUYjg',
    appId: '1:955735179343:web:d5d08746c9e13360a36a3a',
    messagingSenderId: '955735179343',
    projectId: 'instructor-1d9b7',
    authDomain: 'instructor-1d9b7.firebaseapp.com',
    storageBucket: 'instructor-1d9b7.firebasestorage.app',
    measurementId: 'G-EZBH2Q4EDQ',
  );
}
